import { useState, useEffect } from "react";
import Head from "next/head";
import type { Tables } from "~/types_db.ts";

export default function ArtistsView() {
  const [artists, setArtists] = useState<Tables<"Artist">[]>([]);

  useEffect(() => {
    fetch("/api/artists")
      .then((response) => response.json())
      .then(({ Artist: data }) => setArtists(data));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {artists.map((artist) => (
          <div key={artist.id}>{artist.name}</div>
        ))}
      </div>
    </>
  );
}
